---
trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Release
  jobs:  
  - job: Publish
    displayName: NPM Publish
    steps:

    - checkout: self
      persistCredentials: true

    - task: NodeTool@0
      inputs:
        versionSpec: '18.13.0'
      displayName: 'Install Node.js'

    - script: |
        set -e
        git status
        branchName=$(echo "$(Build.SourceBranch)" | sed -e 's/refs.heads.//')
        git checkout "$branchName"
        git config --global user.email "$BUILD_REQUESTEDFOREMAIL"
        git config --global user.name "$BUILD_QUEUEDBY"
        if ! git diff --staged --quiet || ! git diff-files --quiet; then
          git commit -a -m 'Incidental changes from npm-install [skip ci]'
        fi
        npm version patch -m "Bump version to %s [skip ci]"
      displayName: 'Update version'

    - task: Npm@1
      inputs:
        command: 'publish'
        publishRegistry: 'useFeed'
        publishFeed: 'Stay/PMS'

    - script: |
        git push
      displayName: 'Commit new version'
